
var assignments = [
    {0: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'AAML Foundation - Development',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {1: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'AAPA - SOW#2',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {2: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'Amherst - SOW#2 (MVP Dev)',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {3: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'Bluebird Payment Processing',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {4: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'Brief Media',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {5: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'Clinical Pathology - SOW#1',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {6: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'Dimensional Fund Advisors',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {7: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'Gerdau SOW#1',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {8: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'Globeo SOW#3',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {9: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'IHT Observer',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {10: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'IHT Spirit',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {11: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'KinderMorgan - SOW#2',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {12: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'KWKC - SOW#4',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {13: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'Palaterra (Platform)',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {14: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'PRAXENT - Internal Time',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {15: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'PRAXENT - Marketing',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {16: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'PRAXENT - Operations',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {17: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'PRAXENT - Sales',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {18: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'Sysco - SOW#5 - April 2018 (change order) MSOD',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
    {19: 
        {all_day_assignment: true,
            allocation_mode: 'hours_per_day',
            assignable_id: 14460,
            bill_rate: null,
            bill_rate_id: null,
            created_at: '2018-04-19T17:20:13Z',
            description: 'Van Brunt Energy',
            ends_at: '2018-08-18',
            hours_per_day: 1,
            id: 92566,
            repetition_id: null,
            resource_request_id: null,
            starts_at: '2018-04-19',
            status: null,
            status_option_id: null,
            updated_at: '2018-04-19T17:20:13Z',
            user_id: 2814
        }
    },
];


var hasAssignment = function(assignmentDescription) {
    var i = null;
    for (i = 0; assignments.length > i; i += 1) {
        if (assignment[i].description.indexOf(assignmentDescription.toLowerCase()) >= 0) {
            return true;
        }
        else {
            return false;
        }
    }
};

// How To Efficiently Search a JSON Array
// http://mattsnider.com/how-to-efficiently-search-a-json-array/
// Note: This has potential, but since assignment description can be more than one word,
//       it's not really like the one-word tags in the example
